//Diagram adapted from existing provided AB3 class diagram and Modulo, AY19/20 Sem 2

@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Logic {
    package Parser {
        Interface Parser <<Interface>>
        Class FindCommandParser
    }

    package Command {
        Class "{abstract}\n Command" as Command
        Class FindCommand
    }
}

FindCommandParser ..|> Parser
FindCommandParser ..> FindCommand
FindCommand --|>Command

@enduml
